POST http://localhost:5000/register
Content-Type: application/json

{
    "firstname":"llmm",
    "lastname":"ezzidin",
    "email":"jnn@gmail.com",
    "username":"mxcvmx",
    "password":"124455"
}

###
GET http://localhost:5000/getuser

###
GET http://localhost:5000/getfile


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "jnn@gmail.com",
    "password":"124455"
}
###
POST http://localhost:5000/message
Content-Type: application/json

{
    "message": "hallo from message"
}

###

POST http://localhost:5000/newmatch
Content-Type: application/json

{
    "matchTarget":       "61a8a0d8930564e8d6837b55",
    "matchInitiator":    "61a8a1f8930564e8d6837b57"
}

###


GET http://localhost:5000/allmatches
Content-Type: application/json


###

POST http://localhost:5000/allmatchessingleuser
Content-Type: application/json

{
    { "user1-ID": "WJ485f", "user2-ID": "KL934b", "isMatch": true }
}
